name: サンプルコードの動作確認

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-sample:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai
    
    - name: Run Python sample
      env:
        AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
        AZURE_OPENAI_ENDPOINT: ${{ vars.AZURE_OPENAI_ENDPOINT }}
      run: |
        python samples/python/hello_ai.py

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install Node.js dependencies
      working-directory: samples/nodejs
      run: npm install
    
    - name: Run Node.js sample
      working-directory: samples/nodejs
      env:
        AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
        AZURE_OPENAI_ENDPOINT: ${{ vars.AZURE_OPENAI_ENDPOINT }}
      run: npm start

    - name: Install LangChain dependencies
      run: |
        pip install langchain==0.3.18
    
    - name: Run LangChain sample
      env:
        AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
        AZURE_OPENAI_ENDPOINT: ${{ vars.AZURE_OPENAI_ENDPOINT }}
      run: |
        python samples/langchain/hello_ai.py
